import type { TradingPair } from "@/types";

export const MOCK_TRADING_PAIRS: TradingPair[] = [
  {
    symbol: "BTCUSDT",
    baseAsset: "BTC",
    quoteAsset: "USDT",
    name: "Bitcoin",
    price: 43250.5,
    change24h: 2.34,
  },
  {
    symbol: "ETHUSDT",
    baseAsset: "ETH",
    quoteAsset: "USDT",
    name: "Ethereum",
    price: 2280.75,
    change24h: -1.23,
  },
  {
    symbol: "BNBUSDT",
    baseAsset: "BNB",
    quoteAsset: "USDT",
    name: "BNB",
    price: 315.25,
    change24h: 0.85,
  },
  {
    symbol: "XRPUSDT",
    baseAsset: "XRP",
    quoteAsset: "USDT",
    name: "XRP",
    price: 0.625,
    change24h: -0.45,
  },
  {
    symbol: "SOLUSDT",
    baseAsset: "SOL",
    quoteAsset: "USDT",
    name: "Solana",
    price: 98.5,
    change24h: 3.12,
  },
  {
    symbol: "ADAUSDT",
    baseAsset: "ADA",
    quoteAsset: "USDT",
    name: "Cardano",
    price: 0.485,
    change24h: -1.25,
  },
  {
    symbol: "DOGEUSDT",
    baseAsset: "DOGE",
    quoteAsset: "USDT",
    name: "Dogecoin",
    price: 0.082,
    change24h: 1.85,
  },
  {
    symbol: "MATICUSDT",
    baseAsset: "MATIC",
    quoteAsset: "USDT",
    name: "Polygon",
    price: 0.875,
    change24h: -0.65,
  },
  {
    symbol: "LTCUSDT",
    baseAsset: "LTC",
    quoteAsset: "USDT",
    name: "Litecoin",
    price: 72.5,
    change24h: 0.95,
  },
  {
    symbol: "LINKUSDT",
    baseAsset: "LINK",
    quoteAsset: "USDT",
    name: "Chainlink",
    price: 14.25,
    change24h: 2.15,
  },
  {
    symbol: "DOTUSDT",
    baseAsset: "DOT",
    quoteAsset: "USDT",
    name: "Polkadot",
    price: 7.15,
    change24h: -0.35,
  },
  {
    symbol: "AVAXUSDT",
    baseAsset: "AVAX",
    quoteAsset: "USDT",
    name: "Avalanche",
    price: 36.75,
    change24h: 1.45,
  },
  {
    symbol: "UNIUSDT",
    baseAsset: "UNI",
    quoteAsset: "USDT",
    name: "Uniswap",
    price: 6.25,
    change24h: 0.75,
  },
  {
    symbol: "ATOMUSDT",
    baseAsset: "ATOM",
    quoteAsset: "USDT",
    name: "Cosmos",
    price: 9.85,
    change24h: -0.55,
  },
  {
    symbol: "ETCUSDT",
    baseAsset: "ETC",
    quoteAsset: "USDT",
    name: "Ethereum Classic",
    price: 23.45,
    change24h: 0.25,
  },
  {
    symbol: "FILUSDT",
    baseAsset: "FIL",
    quoteAsset: "USDT",
    name: "Filecoin",
    price: 4.25,
    change24h: -1.15,
  },
  {
    symbol: "TRXUSDT",
    baseAsset: "TRX",
    quoteAsset: "USDT",
    name: "TRON",
    price: 0.105,
    change24h: 0.35,
  },
  {
    symbol: "NEOUSDT",
    baseAsset: "NEO",
    quoteAsset: "USDT",
    name: "NEO",
    price: 12.5,
    change24h: -0.85,
  },
  {
    symbol: "ALGOUSDT",
    baseAsset: "ALGO",
    quoteAsset: "USDT",
    name: "Algorand",
    price: 0.185,
    change24h: 0.15,
  },
  {
    symbol: "VETUSDT",
    baseAsset: "VET",
    quoteAsset: "USDT",
    name: "VeChain",
    price: 0.032,
    change24h: 0.65,
  },
];

export const CHART_TIMEFRAMES = [
  { value: "1m", label: "1m", interval: "1m" },
  { value: "5m", label: "5m", interval: "5m" },
  { value: "15m", label: "15m", interval: "15m" },
  { value: "1h", label: "1H", interval: "1h" },
  { value: "4h", label: "4H", interval: "4h" },
  { value: "1d", label: "1D", interval: "1d" },
  { value: "1w", label: "1W", interval: "1w" },
];
